package service

import "errors"

var (
	ErrInvalidParam       = errors.New("invalid parameter")
	ErrInvalidCredentials = errors.New("invalid username or password")
	ErrAccountInactive    = errors.New("account is inactive")
	ErrAccountLocked      = errors.New("account is locked")
	ErrForbidden          = errors.New("forbidden")
	ErrInvalidPassword    = errors.New("invalid password")
	ErrInvalidUserStatus  = errors.New("invalid user status")
	ErrInvalidUsername    = errors.New("invalid username")
	ErrUsernameExists     = errors.New("username already exists")
	ErrCannotDisableSelf  = errors.New("cannot disable current user")
	ErrCannotDeleteSelf   = errors.New("cannot delete current user")
	ErrCannotDeleteRoot   = errors.New("cannot delete root user")
	ErrCannotRenameRoot   = errors.New("root username cannot be changed")
	ErrInvalidRoleCode    = errors.New("invalid role code")
	ErrInvalidRoleName    = errors.New("invalid role name")
	ErrRoleCodeExists     = errors.New("role code already exists")
	ErrRoleNotFound       = errors.New("role not found")
	ErrSystemRoleLocked   = errors.New("system role is immutable")
	ErrRoleInUse          = errors.New("role is still assigned to users")
	ErrInvalidRoleList    = errors.New("invalid role list")
	ErrCannotDemoteRoot   = errors.New("root user must keep root role")

	ErrInvalidOrganizationType   = errors.New("invalid organization type")
	ErrInvalidOrganizationStatus = errors.New("invalid organization status")
	ErrOrganizationNotFound      = errors.New("organization not found")
	ErrOrganizationInactive      = errors.New("organization is inactive")
	ErrOrganizationInUse         = errors.New("organization still has child records")

	ErrInvalidDepartmentStatus = errors.New("invalid department status")
	ErrDepartmentNotFound      = errors.New("department not found")
	ErrDepartmentInUse         = errors.New("department still has child records")

	ErrInvalidPositionLevelStatus = errors.New("invalid position level status")
	ErrPositionLevelNotFound      = errors.New("position level not found")
	ErrPositionLevelCodeExists    = errors.New("position level code already exists")
	ErrSystemPositionLevelLocked  = errors.New("system position level code is immutable")
	ErrPositionLevelInUse         = errors.New("position level is still assigned to employees")

	ErrInvalidEmployeeStatus = errors.New("invalid employee status")
	ErrEmployeeNotFound      = errors.New("employee not found")
	ErrEmployeeInUse         = errors.New("employee still has dependent records")

	ErrInvalidTransferType   = errors.New("invalid transfer type")
	ErrInvalidEffectiveDate  = errors.New("effective date is required")
	ErrInvalidYearStatus     = errors.New("invalid year status")
	ErrYearNotFound          = errors.New("assessment year not found")
	ErrYearAlreadyExists     = errors.New("assessment year already exists")
	ErrInvalidYearTransition = errors.New("invalid year status transition")
	ErrYearAlreadyEnded      = errors.New("assessment year already ended")
	ErrAssessmentReadOnly    = errors.New("assessment data is read-only in completed status")
	ErrAssessmentNotActive   = errors.New("assessment year is not active")

	ErrInvalidPeriodStatus     = errors.New("invalid period status")
	ErrPeriodNotFound          = errors.New("assessment period not found")
	ErrInvalidPeriodTransition = errors.New("invalid period status transition")
	ErrInvalidPeriodTemplate   = errors.New("invalid assessment period template")
	ErrPeriodLocked            = errors.New("assessment period is locked")
	ErrPeriodNotActive         = errors.New("assessment period is not active")

	ErrRuleNotFound              = errors.New("assessment rule not found")
	ErrRuleAlreadyExists         = errors.New("assessment rule already exists for the same dimension")
	ErrInvalidRulePeriodCode     = errors.New("invalid rule period code")
	ErrInvalidRuleObjectType     = errors.New("invalid rule object type")
	ErrInvalidRuleObjectCategory = errors.New("invalid rule object category")
	ErrInvalidRuleName           = errors.New("invalid rule name")
	ErrInvalidRuleModules        = errors.New("invalid rule modules")
	ErrRuleWeightSumInvalid      = errors.New("weighted module sum must be exactly 1.0000")
	ErrVoteGroupWeightInvalid    = errors.New("vote group weight sum must be exactly 1.0000")
	ErrInvalidModuleCode         = errors.New("invalid module code")
	ErrInvalidExpression         = errors.New("invalid custom expression")

	ErrDirectScoreNotFound       = errors.New("direct score not found")
	ErrDirectScoreExists         = errors.New("direct score already exists")
	ErrInvalidScoreValue         = errors.New("score is out of range")
	ErrInvalidScoreModule        = errors.New("invalid score module for direct input")
	ErrAssessmentObjectNotFound  = errors.New("assessment object not found")
	ErrInvalidImportTemplateType = errors.New("invalid import template type")
	ErrImportFileRequired        = errors.New("import file is required")
	ErrImportFileInvalid         = errors.New("import file is invalid or unsupported")
	ErrImportNoValidRows         = errors.New("no valid rows to import")
	ErrImportRowLimitExceeded    = errors.New("import row count exceeds limit 5000")
	ErrInvalidExtraPointType     = errors.New("invalid extra point type")
	ErrInvalidExtraPointValue    = errors.New("extra points must be in range -20 to +20")
	ErrExtraPointReasonEmpty     = errors.New("extra point reason is required")
	ErrExtraPointNotFound        = errors.New("extra point record not found")

	ErrInvalidVoteModule      = errors.New("invalid score module for vote task")
	ErrInvalidVoteTaskStatus  = errors.New("invalid vote task status")
	ErrVoteTaskNotFound       = errors.New("vote task not found")
	ErrVoteTaskLocked         = errors.New("vote task is already completed")
	ErrVoteTaskNotResettable  = errors.New("only completed or expired vote task can be reset")
	ErrVoteTaskForbidden      = errors.New("vote task does not belong to current user")
	ErrInvalidVoteGradeOption = errors.New("invalid vote grade option")

	ErrCalcDependencyCycle = errors.New("calculation dependency graph has cycle")
	ErrCalcExpressionEval  = errors.New("failed to evaluate custom expression")

	ErrBackupNotFound           = errors.New("backup record not found")
	ErrInvalidBackupType        = errors.New("invalid backup type")
	ErrBackupConfirmMismatch    = errors.New("restore confirmation mismatch")
	ErrInvalidBackupRestoreMode = errors.New("invalid backup restore mode")
	ErrBackupTargetMismatch     = errors.New("backup target organization mismatch")
	ErrBackupPackageBroken      = errors.New("backup package is invalid or corrupted")

	ErrAuditLogNotFound         = errors.New("audit log not found")
	ErrAuditRollbackUnsupported = errors.New("audit log does not support rollback")

	ErrInvalidSettingKey   = errors.New("invalid setting key")
	ErrInvalidSettingValue = errors.New("invalid setting value")
)
